# Site
title:          Le Quang Long
bio:            'A short note in my developer life!'
description:    "This is a personal blog I am writing to note some experiences in my developer life."
picture:        'assets/img/avatar.png'
locale:         ja_JP
url:            https://lequanglong.github.io


# Jekyll
permalink:      /:title/
markdown:       kramdown
highlighter:    rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  parse_block_html: true
sass:
  sass_dir: _sass
  style: compressed

# Social
# if you don't have any of social below, comment the line.
#email:
twitter: le_quanglong
facebook: kaka.ruchi.3
google:
  #plus: #username
  analytics: UA-104382870-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
github: lequanglong
#stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin: username
#xing: username
#instagram: username
#lastfm: username
#tumblr: username
#pinterest: username
#foursquare: username
#steam: username
#dribbble: username
youtube: UCmamWDEYsNk7Zr_BOlASztQ
#soundcloud: username
#weibo: username
#flickr: username
#codepen: username

# Paginate
# if you don't need pagination, comment the *paginate* configs below
 paginate: 5
 paginate_path: "blog/:num/"


# Comments
disqus_shortname: lequanglong-github-io


# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
